export default {
  SET_THEME: "setTheme",
  SET_TAB_NAME: "setTabName",
  CHANGE_ACTIVE_CHAT: "changeActiveChat",
  SET_CHAT_LIST: "setChatList",
  ADD_CHAT_LIST: "addChatList",
  UPDATE_MSG_LIST: "updateMsgList",
  CLEAR_MSG_LIST: "clearMsgList",
  SET_PERSONAL: "setPersonal",
  CHANGE_USER_INFO: "changeUserInfo",
  CHANGE_USER_INFO_VISIBLE: "changeUserInfoVisible",
  CHANGE_FRIEND_REQUEST: "changeFriendRequest",
  SET_FRIEND_LIST: "setFriendList",
  SET_MSG_TIPS: "setMsgTips",
};
